version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./public/uploads:/var/www/html/uploads
    environment:
      - MYSQL_HOST=db  # Use the service name 'db' (Docker's internal DNS)
      - MYSQL_PORT=3306  # Explicitly define the port
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=task_manager
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=task_manager
      - MYSQL_ROOT_HOST=%  # Allow root access from any host
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password  # Fix auth issues
    # Optional: Explicitly bind MySQL to all interfaces
    # command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

volumes:
  db_data:

networks:
  app-network:  # Create a dedicated network