version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./public/uploads:/var/www/html/uploads
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Use the DATABASE_URL environment variable
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_user"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:  # Create a dedicated network
