version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./public/uploads:/var/www/html/uploads
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=task_manager
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=task_manager
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: